spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.client.registration.google.client-id=${SPRING_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.client-id=${SPRING_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${SPRING_GITHUB_CLIENT_SECRET}

jwt.secret=${SPRING_JWT_SIGNING_KEY}
