#DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#Redis
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

#Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

#OAuth 2.0
#OAuth 2.0 Google
spring.security.oauth2.client.registration.google.client-id=${SPRING_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${SPRING_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

#OAuth 2.0 @GitHub
spring.security.oauth2.client.registration.github.client-id=${SPRING_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${SPRING_GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github

server.forward-headers-strategy=framework

#Secrets
jwt.secret=${SPRING_JWT_SIGNING_KEY}

#FrontendURL
app.frontend.url=${SPRING_FRONT_END_URL}

server.servlet.context-path=/api